### ISSUE TITLE
numeric sum up bug

### ISSUE THREAD

**Issue by ZZzzGeorge** [yavuztor/JsonLogic.Net#9]
Rule:
{
  "+": [
    { "var": "RATE_1" },
    { "var": "RATE_2" }
  ]
}
Data1 : 36.54+22.309 expected 58.849, but actual 58.849000000000004
{
  "RATE_1": 36.54,
  "RATE_2": 22.309
}
Data2 : 36.54+22.308 expected 58.848, actual 58.848 ----- OK
{
  "RATE_1": 36.54,
  "RATE_2": 22.308
}
Data3 : 36.54+22.307 expected 58.847, but actual 58.846999999999994
{
  "RATE_1": 36.54,
  "RATE_2": 22.307
}
Data4 : 36.54+22.306 expected 58.846, but actual 58.846000000000004
{
  "RATE_1": 36.54,
  "RATE_2": 22.306
}
Data5 : 36.54+22.305 expected 58.845, actual 58.845 ----- OK
{
  "RATE_1": 36.54,
  "RATE_2": 22.305
}

Not very consistent..........which would be determined wrongly as false when using it in "==" like

{
  "===":[
    {
      "+": [
        { "var": "RATE_1" },
        { "var": "RATE_2" }
    ]
   },{"var":"TOTAL"}]
}
with data
{
  "RATE_1": 36.54,
  "RATE_2": 22.309,
  "TOTAL": 58.849
}

**Comment by yavuztor** [comment]
This sounds like double vs decimal issue. I will check this with the is implementation to see how that results. Meanwhile, you can  do a pull request, if you have a solution.

**Comment by ZZzzGeorge** [comment]
How about Convert.ToDecimal rather than Convert.ToDouble?

**Comment by yavuztor** [comment]
It might get inconsistent with jsonlogic js, You can try your rule and data in [http://jsonlogic.com/play.html](http://jsonlogic.com/play.html) to see what is returned.

I think it is better to perform a range check on numbers, than converting all numbers to decimals. We can add a new operator to do this. You can use `EvaulateOperators.AddOperator` method to add custom operators into the evaluator. This way, you can expand the out-of-the-box operators to include operators that satisfy any requirements you might have.

I will add a new operator `within` into out-of-the-box operators. It will take 3 args: first 2 will be the numbers to compare and third one will be the precision. it will take the difference of the numbers and return `true` if their difference is less than the precision value. It  will return `false` otherwise.

**Comment by yavuztor** [comment]
I added a new operator `within` into the default operators list. It can be utilized to do comparisons with numbers.
